Leaderboard
Hill-Valley-Team/space-game pull request #12
Opened 2022-01-10 12:27 UTC by AngryFennec

2022-01-10 12:28 UTC, AngryFennec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница лидерборда / Вёрстка](https://trello.com/c/V6wuRRuM/10-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%BB%D0%B8%D0%B4%D0%B5%D1%80%D0%B1%D0%BE%D1%80%D0%B4%D0%B0-%D0%B2%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B0)

2022-01-10 12:28 UTC, AngryFennec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Настроить husky/pre-commit](https://trello.com/c/xuJT5FF2/27-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-husky-pre-commit)

2022-01-11 12:17 UTC, diglibum requested changes

2022-01-11 12:17 UTC, diglibum commented on src/pages/LeaderBoardPage/LeaderBoardPage.tsx
> +  }, []);
Тут линтер ругается что "React Hook useCallback has a missing dependency: 'navigate'. Either include it or remove the dependency array."

2022-01-11 12:17 UTC, diglibum commented on src/pages/LeaderBoardPage/LeaderBoardPage.tsx
> +        <div className={b('table-header')}>
Тут можно создать ещё один блок
const h = block('table-header');

2022-01-11 12:17 UTC, diglibum commented on src/pages/LeaderBoardPage/LeaderBoardPage.tsx
> +            className={b('table-header-btn')}
Тогда тут можно писать: className={h('button')}

2022-01-11 12:17 UTC, diglibum commented on src/pages/LeaderBoardPage/LeaderBoardPage.tsx
> +            className={b('table-header-btn')}
className={h('button')}

2022-01-11 12:17 UTC, diglibum commented on src/pages/LeaderBoardPage/LeaderBoardPage.tsx
> +  const onSortBtnClick = useCallback((event) => {
а сама сортировка у нас не в этом спринте должна быть реализована?

2022-01-11 12:17 UTC, diglibum commented on src/pages/LeaderBoardPage/leaderBoardPage.css
> +  & .page-container {
тут, наверное, лишнее писать селектор &

2022-01-11 12:17 UTC, diglibum commented on src/pages/LeaderBoardPage/leaderBoardPage.css
> +    &--active {
&_active - модификаторы мы везде раньше писали в нижнем подчёркивании

2022-01-12 18:34 UTC, AngryFennec commented on src/pages/LeaderBoardPage/LeaderBoardPage.tsx
> +  }, []);
это вроде ворнинг?

2022-01-12 18:35 UTC, AngryFennec commented on src/pages/LeaderBoardPage/LeaderBoardPage.tsx
> +  const onSortBtnClick = useCallback((event) => {
мне показалось логичным делать сортировку уже с данными. Пока там статичная верстка - сложно сортировать

2022-01-13 11:06 UTC, closed without merging