fullscreen
Hill-Valley-Team/space-game pull request #29
Opened 2022-01-21 16:18 UTC by AngryFennec

2022-01-21 16:29 UTC, diglibum commented
У меня не работает на F11 на маке. Может другую клавишу?  Я попробовала на Q, например - заработало.

2022-01-21 16:31 UTC, diglibum requested changes
У меня не работает на F11 на маке. Может другую клавишу? Я попробовала на Q, например - заработало.

2022-01-21 17:05 UTC, AngryFennec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавьте минимум одно Web API.](https://trello.com/c/SusLC4uE/44-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D1%8C%D1%82%D0%B5-%D0%BC%D0%B8%D0%BD%D0%B8%D0%BC%D1%83%D0%BC-%D0%BE%D0%B4%D0%BD%D0%BE-web-api)

2022-01-23 07:08 UTC, diglibum approved these changes

2022-01-23 07:08 UTC, diglibum commented on src/utils/fullscreen.ts
> +  } else {
Тут можно else if

2022-01-23 11:04 UTC, merged