Sprint 5
Hill-Valley-Team/space-game pull request #5
Opened 2021-12-19 08:03 UTC by diglibum

2021-12-19 08:10 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Настроить Webpack-сборку с React, Typescript, препроцессорами.](https://trello.com/c/2gYvBC1z/25-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-webpack-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D1%83-%D1%81-react-typescript-%D0%BF%D1%80%D0%B5%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D1%80%D0%B0%D0%BC%D0%B8)

2021-12-19 08:10 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Указать версию NodeJS в .nvmrc или engine в package.json.](https://trello.com/c/tGFoE2Bc/24-%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D1%8C-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8E-nodejs-%D0%B2-nvmrc-%D0%B8%D0%BB%D0%B8-engine-%D0%B2-packagejson)

2021-12-19 08:10 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница Регистрации / Подключить API](https://trello.com/c/FxBTSn7n/13-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-api)

2021-12-19 08:11 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить API авторизации и Logout](https://trello.com/c/ejzgcokr/28-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-api-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-%D0%B8-logout)

2021-12-19 08:11 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить React Router](https://trello.com/c/HUDauUmH/16-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-react-router)

2021-12-19 08:12 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать валидацию форм](https://trello.com/c/NsXBxhuX/23-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D1%8E-%D1%84%D0%BE%D1%80%D0%BC)

2021-12-19 08:12 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница регистрации / Вёрстка](https://trello.com/c/qrJrsaVu/6-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D0%B2%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B0)

2021-12-19 08:12 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница регистрации / Дизайн](https://trello.com/c/mjZiXaj9/5-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD)

2021-12-19 08:13 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница входа / Вёрстка](https://trello.com/c/Ef4I8xb3/4-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0-%D0%B2%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B0)

2021-12-19 09:12 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница 404 / Верстка на React](https://trello.com/c/You07OSO/31-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-404-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0-%D0%BD%D0%B0-react)

2021-12-19 09:29 UTC, ivan-infro requested changes
👀

2021-12-21 17:52 UTC, ivan-infro requested changes

2021-12-21 17:52 UTC, ivan-infro commented on package.json
> +    "node": "16.13.1"
Строгое ограничение версии вплоть до патча, действительно ли поддерживается только этот выпуск nodejs?)

https://semver.org

Рекомендую изменить хотя бы на ^16.13

2021-12-21 17:52 UTC, ivan-infro commented on .gitignore
> +.idea
Не хватает еще, как минимум, ОС-специфичных файлов типа .DS_Store

Рекомендую воспользоваться шаблонами отсюда: https://github.com/github/gitignore

2021-12-21 17:52 UTC, ivan-infro commented on package.json
> +  "description": "Project developed during cource Middle Frontend Developer at Yandex Practicum",
*course :) 

Также не актуальные ссылки на репозиторий и issues, хорошо бы поправить

2021-12-21 17:52 UTC, ivan-infro commented on src/api/BaseApi.ts
> +import axios, { AxiosInstance } from 'axios';
Использование axios немного упрощает работу с http запросами, но на проектах, где важно добиться минимального размера бандла достаточно использовать fetch

2021-12-21 17:52 UTC, ivan-infro commented on src/components/Footer/Footer.tsx
> +import { FooterProps } from './types';
Далее про оформление кода, текущий вариант тоже нормальный:

Если описывать тип props в том же файле, что и сам компонент, то, во-первых, не надо будет переходить в другой файл, чтобы узнать интерфейс компонента, а во-вторых, не надо будет экспортировать/импортировать этот тип. Это предотвратит использование типа ComponentProps во вне, что хорошо, потому что правильней использовать React.ComponentProps

2021-12-21 17:52 UTC, ivan-infro commented on src/components/Footer/types.ts
> +export type FooterProps = {
PropsWithChildren<{ className?: string }>

2021-12-21 17:52 UTC, ivan-infro commented on src/components/Form/Form.tsx
> +  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
👍 Отличный выбор именования обработчиков
 https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md

2021-12-21 17:52 UTC, ivan-infro commented on src/controllers/utils/prepareDataToRequest.ts
> +  fields.reduce((acc, field) => ({ ...acc, [field]: String(formData.get(field)) }), {});
⚠️ Здесь на каждой итерации целиком копируется объект "acc", это может очень плохо сказаться на производительности

Сравните текущую и менее "модную" (без reduce) реализации на скорость:

https://perf.link/#eyJpZCI6InJnbWdvZ3Bwejg0IiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXSIsInRlc3RzIjpbeyJuYW1lIjoiRmluZCBpdGVtIDEwMCIsImNvZGUiOiJkYXRhLnJlZHVjZSgoYWNjLCBmaWVsZCkgPT4gKHsgLi4uYWNjLCBbZmllbGRdOiBTdHJpbmcoZmllbGQpIH0pLCB7fSk7IiwicnVucyI6WzMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDI3LDMwLDI3LDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDMwLDI3LDI3LDI3LDI3LDI3LDMwLDMwLDI3LDI0LDI3LDMwLDMwLDMwLDMwLDMwLDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2LDM2XSwib3BzIjozMX0seyJuYW1lIjoiRmluZCBpdGVtIDIwMCIsImNvZGUiOiJjb25zdCBvYmogPSB7fVxuZm9yIChsZXQgZmllbGQgaW4gZGF0YSkge1xuICBvYmpbZmllbGRdID0gU3RyaW5nKGZpZWxkKTtcbn0iLCJydW5zIjpbMTQ4NzksMTQ3MjksMTUyMjgsMTQ5NjMsMTQ1ODIsMTQ2OTksMTUyMjgsMTQ4ODUsMTQ3NjUsMTM5NzIsMTI3NjIsMTQ2OTksMTI3MTQsMTM4OTEsMTQ2NDIsMTQ5OTAsMTUxMjksMTQ2NjMsMTQ1NjQsMTQ4OTcsMTUwMTgsMTQ5NDIsMTQ3NjUsMTUwOTYsMTUyMTYsMTQ2MzMsMTQ2MDAsMTQ2MzMsMTQ4OTcsMTQxNzEsMTQ3NjUsMTQ3NjUsMTQ3MjYsMTQxOTgsMTUwMzAsMTQ4MzEsMTUxNjIsMTQ5NjMsMTUwOTYsMTQ3NjUsMTQ2OTksMTQ1MDEsMTQ4ODgsMTQ4MTYsMTUwOTYsMTQ4MDQsMTQ4MzEsMTM5MDAsMTUwOTYsMTQ1MDEsMTQ1NTgsMTQ1NjcsMTQ0MzUsMTQ2NzIsMTQxNzEsMTQ1MDEsMTIzODQsMTE5MjEsMTI5MTIsMTI0NTAsMTIyOTQsMTM4NDAsMTM0NDEsMTIyNzYsMTE0MjMsMTMxNzcsMTM1NzMsMTQyMzcsMTQ4MzEsMTQ4MzEsMTQ5NDIsMTgwNzIsMTgyMTksMTgyMDQsMTc4NzMsMTgwMDYsMTgxNzEsMTgyMDQsMTgxMzgsMTgyMDQsMTgwNzIsMTc5MjQsMTgxMzgsMTgzNDgsMTgyMjgsMTg0MDIsMTg1MzQsMTgyMzcsMTgxMzgsMTgxNTksMTgzMTIsMTgzNTEsMTgzMzYsMTgyMDQsMTgyMDQsMTgyNzAsMTgyNjcsMTg0MzgsMTgxMzgsMTgyMDRdLCJvcHMiOjE1NDc3fV0sInVwZGF0ZWQiOiIyMDIxLTEyLTIxVDE3OjQwOjQzLjUxMloifQ%3D%3D

2021-12-21 17:52 UTC, ivan-infro commented on src/store/user/actions.ts
> +  const response = await authController.getUserInfo();
Необходимо хотя бы обернуть в try catch

Еще лучше, если "упавший" запрос отразится на состоянии store

2021-12-21 17:52 UTC, ivan-infro commented on src/store/user/slice.ts
> +      .addCase(getUserData.pending, (state) => {
Чтобы не писать много подобного кода, используйте RTK Query: https://redux-toolkit.js.org/rtk-query/overview

2021-12-21 17:52 UTC, ivan-infro commented on webpack.common.js
> +  output: {
Т.к. вам понадобится использовать этот же бандл на сервере, используйте тип сборки UMD, или промежуточную сборку в ES module

https://dev.to/iggredible/what-the-heck-are-cjs-amd-umd-and-esm-ikm

2021-12-21 17:52 UTC, ivan-infro commented on webpack.common.js
> +          ['gifsicle', { interlaced: true }],
FYI: вот эти плагины используют бинарные зависимости :)

2021-12-21 18:02 UTC, ivan-infro commented
Отображается сразу две иконки "Показать пароль" (кастомная и системная), по нажатию на них ничего не происходит

Браузер Edge (Chromium based), но системная кнопка "показать пароль" есть и в остальных браузерах

<img width="355" alt="image" src="https://user-images.githubusercontent.com/5419627/146976991-09090653-46e1-40dc-b7b9-0d795d8bac1c.png">

2021-12-21 18:04 UTC, ivan-infro commented
Корректный email адрес не проходит вариацию

<img width="311" alt="image" src="https://user-images.githubusercontent.com/5419627/146977368-048b4955-c220-412c-b62a-e6f2b921e288.png">

2021-12-21 18:08 UTC, ivan-infro commented
Обращайте внимание на Tab-навигацию. Сейчас при переходе из поля "Пароль" по Tab'у фокус получает кнопка "Показать пароль" следующей строки

2021-12-21 18:12 UTC, ivan-infro requested changes

2021-12-21 18:12 UTC, ivan-infro commented on src/controllers/AuthController.ts
> +    const preparedData = prepareDataToRequest(signInRequestFields, formData) as SignInRequest;
Избегайте приведения типов, с ним вы можете пропустить реальную ошибку
В данном случае лучше использовать generic тип https://www.typescriptlang.org/docs/handbook/2/generics.html

2021-12-26 12:25 UTC, diglibum commented on package.json
> +  "description": "Project developed during cource Middle Frontend Developer at Yandex Practicum",
Упсик )

2021-12-26 12:26 UTC, diglibum commented on src/api/BaseApi.ts
> +import axios, { AxiosInstance } from 'axios';
@ivan-infro можем оставить на следующий спринт? Добавлю в трелло.

2021-12-26 12:36 UTC, diglibum commented on src/components/Footer/Footer.tsx
> +import { FooterProps } from './types';
Если этот момент не критичен, оставила бы пока как есть.  
> Это предотвратит использование типа ComponentProps во вне, что хорошо, потому что правильней использовать React.ComponentProps

интересно! не задумывалась )

2021-12-26 12:56 UTC, diglibum commented on src/controllers/utils/prepareDataToRequest.ts
> +  fields.reduce((acc, field) => ({ ...acc, [field]: String(formData.get(field)) }), {});
Посмотрела. Ничего себе!

2021-12-26 19:48 UTC, diglibum commented on src/store/user/slice.ts
> +      .addCase(getUserData.pending, (state) => {
Предлагаю изменить когда будем делать следующие редьюсеры (для форума и лидерборда)

2021-12-27 19:45 UTC, ivan-infro commented on src/api/BaseApi.ts
> +import axios, { AxiosInstance } from 'axios';
Можно оставить axios, про fetch это на будущее, чтобы не тянули его "по умолчанию" в новые проекты

2021-12-29 12:27 UTC, ivan-infro approved these changes

2022-01-02 14:34 UTC, merged